# Generated by Django 2.1.7 on 2019-02-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('ship_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hull_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sprite_name', models.CharField(blank=True, max_length=150, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('hull_size', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('center', models.CharField(blank=True, max_length=10, null=True)),
                ('armor_rating', models.FloatField(blank=True, null=True)),
                ('acceleration', models.FloatField(blank=True, null=True)),
                ('field_8_6_5_4', models.FloatField(blank=True, null=True)),
                ('cargo', models.FloatField(blank=True, null=True)),
                ('deceleration', models.FloatField(blank=True, null=True)),
                ('flux_dissipation', models.FloatField(blank=True, null=True)),
                ('fuel', models.FloatField(blank=True, null=True)),
                ('fuel_ly', models.FloatField(blank=True, null=True)),
                ('hitpoints', models.FloatField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('max_crew', models.IntegerField(blank=True, null=True)),
                ('max_flux', models.FloatField(blank=True, null=True)),
                ('max_speed', models.FloatField(blank=True, null=True)),
                ('max_turn_rate', models.FloatField(blank=True, null=True)),
                ('min_crew', models.IntegerField(blank=True, null=True)),
                ('ordnance_points', models.IntegerField(blank=True, null=True)),
                ('shield_arc', models.FloatField(blank=True, null=True)),
                ('shield_efficiency', models.FloatField(blank=True, null=True)),
                ('shield_type', models.CharField(blank=True, max_length=20, null=True)),
                ('shield_upkeep', models.FloatField(blank=True, null=True)),
                ('supplies_month', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ships',
            },
        ),
        migrations.CreateModel(
            name='WeaponSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_info', models.TextField(blank=True, null=True)),
                ('ship_name', models.ForeignKey(blank=True, db_column='ship_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fitting.Ships')),
            ],
            options={
                'db_table': 'weapon_slots',
            },
        ),
    ]
